import "./globals.scss";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import RootServer from "@/components/ServerComponents/root.server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Carteira Financeira",
  description: "Generated by create next app",
  icons : {
    icon: "/assets/icons/favicon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <RootServer>
          {children}
        </RootServer>
      </body>
    </html>
  );
}
